CREATE TABLE IF NOT EXISTS users(
UID INTEGER PRIMARY KEY AUTOINCREMENT,
LastName varchar(255) NOT NULL,
FirstName varchar(255) NOT NULL, Username varchar(255) NOT NULL,
Password varchar(255) NOT NULL);

CREATE TABLE IF NOT EXISTS photos(
UID INTEGER NOT NULL,
DateTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
FilePath varchar(255) NOT NULL,
PRIMARY KEY (UID, DateTime));

CREATE TABLE IF NOT EXISTS weights(
UID INTEGER NOT NULL,
DateTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
Weight REAL NOT NULL,
PRIMARY KEY (UID, DateTime));

CREATE TABLE IF NOT EXISTS heights(
UID INTEGER NOT NULL,
DateTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
Height REAL NOT NULL,
PRIMARY KEY (UID, DateTime));

CREATE TABLE IF NOT EXISTS peakflow(
UID INTEGER NOT NULL,
DateTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
PeakFlow REAL NOT NULL,
PRIMARY KEY (UID, DateTime));